name: Test MySQL Package

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
    paths:
      - 'packages/mysql/**'
  pull_request:
    paths:
      - 'packages/mysql/**'

permissions:
  contents: read
  statuses: write

jobs:
  MAF-MySQL:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -ptestpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --health-start-period=30s
    
    strategy:
      matrix:
        node-version: [22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases

    steps:
      - uses: actions/checkout@v4.2.2
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Wait for MySQL to be ready
        run: |
          until nc -z localhost 3307; do
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL is ready!"
      
      - name: Initialize MySQL database
        run: |
          mysql -h127.0.0.1 -P3307 -uroot -ptestpassword -e "CREATE DATABASE IF NOT EXISTS testdb;"
          if [ -f packages/mysql/init-db.sql ]; then
            mysql -h127.0.0.1 -P3307 -uroot -ptestpassword testdb < packages/mysql/init-db.sql
          fi
      
      - name: Test MySQL Package
        run: npm run test:run -w packages/mysql
        env: 
          ENVIRONMENT: CI
          USE_ENV_VARIABLES: "TRUE"
          MYSQL_SQL_USERNAME: root
          MYSQL_SQL_PASSWORD: testpassword
      
      - name: Status Create Action
        if: ${{ always() }}
        uses: hkusu/status-create-action@v1.0.1
        id: status-create
        with:
          state: ${{ job.status }} 
          sha: ${{ github.sha }}
    
      - name: Show result
        if: always()
        run: echo '${{ steps.status-create.outputs.result }}'
