name: Test AWS Package

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
    paths:
      - 'packages/aws/**'
  pull_request:
    paths:
      - 'packages/aws/**'

jobs:
  MAF-AWS:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases

    steps:
    - uses: actions/checkout@v4.1.7
    - uses: LocalStack/setup-localstack@v0.2.3
      with:
        image-tag: '3.7.2'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.2.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
    - run: mkdir ~/.aws/
    - run: echo -e "[default]\noutput = json\nregion = us-east-1\naws_access_key_id = foo\naws_secret_access_key = bar" > ~/.aws/credentials
    - run: npm ci
    - name: Terraform - apply to localstack
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve
    - run: npm test -w packages/aws
      env: 
       ENVIRONMENT: CI
       USE_ENV_VARIABLES: "TRUE"
       LOCALSTACK_HOSTNAME: localhost
       AWSENV: LOCALSTACK
     
    - name: Status Create Action
      if: ${{ always() }}
      uses: hkusu/status-create-action@v1.0.1
      id: status-create
      with:
        state: ${{ job.status }} 
        sha: ${{ github.sha }}
  
    - name: Show result
      if: always()
      run: echo '${{ steps.status-create.outputs.result }}'
