name: Test PostgreSQL Package

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
    paths:
      - 'packages/postgresql/**'
  pull_request:
    paths:
      - 'packages/postgresql/**'

permissions:
  contents: read
  statuses: write

jobs:
  MAF-PostgreSQL:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testpassword
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=30s
    
    strategy:
      matrix:
        node-version: [22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases

    steps:
      - uses: actions/checkout@v4.2.2
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Wait for PostgreSQL to be ready
        run: |
          until nc -z localhost 5433; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
      
      - name: Initialize PostgreSQL database
        run: |
          if [ -f packages/postgresql/init-db.sql ]; then
            PGPASSWORD=testpassword psql -h localhost -p 5433 -U postgres -d testdb -f packages/postgresql/init-db.sql
          fi
      
      - name: Test PostgreSQL Package
        run: npm run test:run -w packages/postgresql
        env: 
          ENVIRONMENT: CI
          USE_ENV_VARIABLES: "TRUE"
          POSTGRESQL_SQL_USERNAME: postgres
          POSTGRESQL_SQL_PASSWORD: testpassword
      
      - name: Status Create Action
        if: ${{ always() }}
        uses: hkusu/status-create-action@v1.0.1
        id: status-create
        with:
          state: ${{ job.status }} 
          sha: ${{ github.sha }}
    
      - name: Show result
        if: always()
        run: echo '${{ steps.status-create.outputs.result }}'
